# ------------------------------------------------------------
# RESIZE mode — resize the focused window
# (previously CTRL+ALT+h/l/j/k)
keymode=resize
binds=NONE,h,resizewin,-50,+0
binds=NONE,l,resizewin,+50,+0
binds=NONE,k,resizewin,+0,-50
binds=NONE,j,resizewin,+0,+50
bind=NONE,Left,resizewin,-50,+0
bind=NONE,Right,resizewin,+50,+0
bind=NONE,Up,resizewin,+0,-50
bind=NONE,Down,resizewin,+0,+50
bind=NONE,Escape,setkeymode,default
source=./modal_invalid.conf

