# ------------------------------------------------------------
# MOVE mode — move the focused window within the layout
# (previously SUPER+CTRL+h/l/j/k)
keymode=move
binds=NONE,h,exchange_client,left
binds=NONE,l,exchange_client,right
binds=NONE,k,exchange_client,up
binds=NONE,j,exchange_client,down
bind=NONE,Left,exchange_client,left
bind=NONE,Right,exchange_client,right
bind=NONE,Up,exchange_client,up
bind=NONE,Down,exchange_client,down
bind=NONE,Escape,setkeymode,default
source=./modal_invalid.conf

